# Generated by Django 5.2.4 on 2025-08-05 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_url_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_published',
            new_name='is_featured',
        ),
    ]
