# Generated by Django 5.2.4 on 2025-08-04 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('image', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('select category', 'select category'), ('Electronic Products', 'Electronic Products'), ('Beauty Products', 'Beauty Products'), ('Kitchen Products', 'Kitchen Products'), ('Makeup Products', 'Makeup Products')], default='select', max_length=500)),
                ('customer_ID', models.CharField(max_length=6)),
                ('address', models.CharField(max_length=1000)),
                ('quantity', models.IntegerField(max_length=500)),
                ('payment', models.CharField(choices=[('payment way', 'payment way'), ('vodafone cash', 'vodafone cash'), ('paypal', 'paypal'), ('Ebay', 'Ebay'), (' visa', ' visa')], default='select', max_length=100)),
            ],
        ),
    ]
