# Generated by Django 5.2.4 on 2025-08-04 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_orders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='orders',
            new_name='order',
        ),
    ]
