# Generated by Django 5.2.4 on 2025-08-05 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_order_cancelled'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='order',
        ),
    ]
